apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- pgweb.yaml
- postgres.yaml
- postgresService.yaml

namespace: appstudio-qe
secretGenerator:
  - name: quality-dashboard-secrets
    envs:
      - secrets.txt

images:
  - name: quay.io/redhat-appstudio/quality-dashboard-backend
    newName: quay.io/redhat-appstudio/quality-dashboard-backend
    newTag: latest