apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  selector:
    app: quality-dashboard
    component: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432