// Code generated by entc, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"log"

	"github.com/google/uuid"
	"github.com/redhat-appstudio/quality-studio/pkg/storage/ent/db/migrate"

	"github.com/redhat-appstudio/quality-studio/pkg/storage/ent/db/codecov"
	"github.com/redhat-appstudio/quality-studio/pkg/storage/ent/db/prow"
	"github.com/redhat-appstudio/quality-studio/pkg/storage/ent/db/repository"
	"github.com/redhat-appstudio/quality-studio/pkg/storage/ent/db/workflows"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// CodeCov is the client for interacting with the CodeCov builders.
	CodeCov *CodeCovClient
	// Prow is the client for interacting with the Prow builders.
	Prow *ProwClient
	// Repository is the client for interacting with the Repository builders.
	Repository *RepositoryClient
	// Workflows is the client for interacting with the Workflows builders.
	Workflows *WorkflowsClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.CodeCov = NewCodeCovClient(c.config)
	c.Prow = NewProwClient(c.config)
	c.Repository = NewRepositoryClient(c.config)
	c.Workflows = NewWorkflowsClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("db: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("db: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		CodeCov:    NewCodeCovClient(cfg),
		Prow:       NewProwClient(cfg),
		Repository: NewRepositoryClient(cfg),
		Workflows:  NewWorkflowsClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:     cfg,
		CodeCov:    NewCodeCovClient(cfg),
		Prow:       NewProwClient(cfg),
		Repository: NewRepositoryClient(cfg),
		Workflows:  NewWorkflowsClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		CodeCov.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.CodeCov.Use(hooks...)
	c.Prow.Use(hooks...)
	c.Repository.Use(hooks...)
	c.Workflows.Use(hooks...)
}

// CodeCovClient is a client for the CodeCov schema.
type CodeCovClient struct {
	config
}

// NewCodeCovClient returns a client for the CodeCov from the given config.
func NewCodeCovClient(c config) *CodeCovClient {
	return &CodeCovClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `codecov.Hooks(f(g(h())))`.
func (c *CodeCovClient) Use(hooks ...Hook) {
	c.hooks.CodeCov = append(c.hooks.CodeCov, hooks...)
}

// Create returns a create builder for CodeCov.
func (c *CodeCovClient) Create() *CodeCovCreate {
	mutation := newCodeCovMutation(c.config, OpCreate)
	return &CodeCovCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CodeCov entities.
func (c *CodeCovClient) CreateBulk(builders ...*CodeCovCreate) *CodeCovCreateBulk {
	return &CodeCovCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CodeCov.
func (c *CodeCovClient) Update() *CodeCovUpdate {
	mutation := newCodeCovMutation(c.config, OpUpdate)
	return &CodeCovUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CodeCovClient) UpdateOne(cc *CodeCov) *CodeCovUpdateOne {
	mutation := newCodeCovMutation(c.config, OpUpdateOne, withCodeCov(cc))
	return &CodeCovUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CodeCovClient) UpdateOneID(id uuid.UUID) *CodeCovUpdateOne {
	mutation := newCodeCovMutation(c.config, OpUpdateOne, withCodeCovID(id))
	return &CodeCovUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CodeCov.
func (c *CodeCovClient) Delete() *CodeCovDelete {
	mutation := newCodeCovMutation(c.config, OpDelete)
	return &CodeCovDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *CodeCovClient) DeleteOne(cc *CodeCov) *CodeCovDeleteOne {
	return c.DeleteOneID(cc.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *CodeCovClient) DeleteOneID(id uuid.UUID) *CodeCovDeleteOne {
	builder := c.Delete().Where(codecov.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CodeCovDeleteOne{builder}
}

// Query returns a query builder for CodeCov.
func (c *CodeCovClient) Query() *CodeCovQuery {
	return &CodeCovQuery{
		config: c.config,
	}
}

// Get returns a CodeCov entity by its id.
func (c *CodeCovClient) Get(ctx context.Context, id uuid.UUID) (*CodeCov, error) {
	return c.Query().Where(codecov.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CodeCovClient) GetX(ctx context.Context, id uuid.UUID) *CodeCov {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCodecov queries the codecov edge of a CodeCov.
func (c *CodeCovClient) QueryCodecov(cc *CodeCov) *RepositoryQuery {
	query := &RepositoryQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := cc.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(codecov.Table, codecov.FieldID, id),
			sqlgraph.To(repository.Table, repository.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, codecov.CodecovTable, codecov.CodecovColumn),
		)
		fromV = sqlgraph.Neighbors(cc.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CodeCovClient) Hooks() []Hook {
	return c.hooks.CodeCov
}

// ProwClient is a client for the Prow schema.
type ProwClient struct {
	config
}

// NewProwClient returns a client for the Prow from the given config.
func NewProwClient(c config) *ProwClient {
	return &ProwClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `prow.Hooks(f(g(h())))`.
func (c *ProwClient) Use(hooks ...Hook) {
	c.hooks.Prow = append(c.hooks.Prow, hooks...)
}

// Create returns a create builder for Prow.
func (c *ProwClient) Create() *ProwCreate {
	mutation := newProwMutation(c.config, OpCreate)
	return &ProwCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Prow entities.
func (c *ProwClient) CreateBulk(builders ...*ProwCreate) *ProwCreateBulk {
	return &ProwCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Prow.
func (c *ProwClient) Update() *ProwUpdate {
	mutation := newProwMutation(c.config, OpUpdate)
	return &ProwUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProwClient) UpdateOne(pr *Prow) *ProwUpdateOne {
	mutation := newProwMutation(c.config, OpUpdateOne, withProw(pr))
	return &ProwUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProwClient) UpdateOneID(id int) *ProwUpdateOne {
	mutation := newProwMutation(c.config, OpUpdateOne, withProwID(id))
	return &ProwUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Prow.
func (c *ProwClient) Delete() *ProwDelete {
	mutation := newProwMutation(c.config, OpDelete)
	return &ProwDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *ProwClient) DeleteOne(pr *Prow) *ProwDeleteOne {
	return c.DeleteOneID(pr.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *ProwClient) DeleteOneID(id int) *ProwDeleteOne {
	builder := c.Delete().Where(prow.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProwDeleteOne{builder}
}

// Query returns a query builder for Prow.
func (c *ProwClient) Query() *ProwQuery {
	return &ProwQuery{
		config: c.config,
	}
}

// Get returns a Prow entity by its id.
func (c *ProwClient) Get(ctx context.Context, id int) (*Prow, error) {
	return c.Query().Where(prow.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProwClient) GetX(ctx context.Context, id int) *Prow {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProw queries the prow edge of a Prow.
func (c *ProwClient) QueryProw(pr *Prow) *RepositoryQuery {
	query := &RepositoryQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := pr.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(prow.Table, prow.FieldID, id),
			sqlgraph.To(repository.Table, repository.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, prow.ProwTable, prow.ProwColumn),
		)
		fromV = sqlgraph.Neighbors(pr.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ProwClient) Hooks() []Hook {
	return c.hooks.Prow
}

// RepositoryClient is a client for the Repository schema.
type RepositoryClient struct {
	config
}

// NewRepositoryClient returns a client for the Repository from the given config.
func NewRepositoryClient(c config) *RepositoryClient {
	return &RepositoryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `repository.Hooks(f(g(h())))`.
func (c *RepositoryClient) Use(hooks ...Hook) {
	c.hooks.Repository = append(c.hooks.Repository, hooks...)
}

// Create returns a create builder for Repository.
func (c *RepositoryClient) Create() *RepositoryCreate {
	mutation := newRepositoryMutation(c.config, OpCreate)
	return &RepositoryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Repository entities.
func (c *RepositoryClient) CreateBulk(builders ...*RepositoryCreate) *RepositoryCreateBulk {
	return &RepositoryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Repository.
func (c *RepositoryClient) Update() *RepositoryUpdate {
	mutation := newRepositoryMutation(c.config, OpUpdate)
	return &RepositoryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RepositoryClient) UpdateOne(r *Repository) *RepositoryUpdateOne {
	mutation := newRepositoryMutation(c.config, OpUpdateOne, withRepository(r))
	return &RepositoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RepositoryClient) UpdateOneID(id uuid.UUID) *RepositoryUpdateOne {
	mutation := newRepositoryMutation(c.config, OpUpdateOne, withRepositoryID(id))
	return &RepositoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Repository.
func (c *RepositoryClient) Delete() *RepositoryDelete {
	mutation := newRepositoryMutation(c.config, OpDelete)
	return &RepositoryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *RepositoryClient) DeleteOne(r *Repository) *RepositoryDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *RepositoryClient) DeleteOneID(id uuid.UUID) *RepositoryDeleteOne {
	builder := c.Delete().Where(repository.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RepositoryDeleteOne{builder}
}

// Query returns a query builder for Repository.
func (c *RepositoryClient) Query() *RepositoryQuery {
	return &RepositoryQuery{
		config: c.config,
	}
}

// Get returns a Repository entity by its id.
func (c *RepositoryClient) Get(ctx context.Context, id uuid.UUID) (*Repository, error) {
	return c.Query().Where(repository.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RepositoryClient) GetX(ctx context.Context, id uuid.UUID) *Repository {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryWorkflows queries the workflows edge of a Repository.
func (c *RepositoryClient) QueryWorkflows(r *Repository) *WorkflowsQuery {
	query := &WorkflowsQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(repository.Table, repository.FieldID, id),
			sqlgraph.To(workflows.Table, workflows.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, repository.WorkflowsTable, repository.WorkflowsColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCodecov queries the codecov edge of a Repository.
func (c *RepositoryClient) QueryCodecov(r *Repository) *CodeCovQuery {
	query := &CodeCovQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(repository.Table, repository.FieldID, id),
			sqlgraph.To(codecov.Table, codecov.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, repository.CodecovTable, repository.CodecovColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryProw queries the prow edge of a Repository.
func (c *RepositoryClient) QueryProw(r *Repository) *ProwQuery {
	query := &ProwQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(repository.Table, repository.FieldID, id),
			sqlgraph.To(prow.Table, prow.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, repository.ProwTable, repository.ProwColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RepositoryClient) Hooks() []Hook {
	return c.hooks.Repository
}

// WorkflowsClient is a client for the Workflows schema.
type WorkflowsClient struct {
	config
}

// NewWorkflowsClient returns a client for the Workflows from the given config.
func NewWorkflowsClient(c config) *WorkflowsClient {
	return &WorkflowsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `workflows.Hooks(f(g(h())))`.
func (c *WorkflowsClient) Use(hooks ...Hook) {
	c.hooks.Workflows = append(c.hooks.Workflows, hooks...)
}

// Create returns a create builder for Workflows.
func (c *WorkflowsClient) Create() *WorkflowsCreate {
	mutation := newWorkflowsMutation(c.config, OpCreate)
	return &WorkflowsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Workflows entities.
func (c *WorkflowsClient) CreateBulk(builders ...*WorkflowsCreate) *WorkflowsCreateBulk {
	return &WorkflowsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Workflows.
func (c *WorkflowsClient) Update() *WorkflowsUpdate {
	mutation := newWorkflowsMutation(c.config, OpUpdate)
	return &WorkflowsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WorkflowsClient) UpdateOne(w *Workflows) *WorkflowsUpdateOne {
	mutation := newWorkflowsMutation(c.config, OpUpdateOne, withWorkflows(w))
	return &WorkflowsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WorkflowsClient) UpdateOneID(id int) *WorkflowsUpdateOne {
	mutation := newWorkflowsMutation(c.config, OpUpdateOne, withWorkflowsID(id))
	return &WorkflowsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Workflows.
func (c *WorkflowsClient) Delete() *WorkflowsDelete {
	mutation := newWorkflowsMutation(c.config, OpDelete)
	return &WorkflowsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *WorkflowsClient) DeleteOne(w *Workflows) *WorkflowsDeleteOne {
	return c.DeleteOneID(w.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *WorkflowsClient) DeleteOneID(id int) *WorkflowsDeleteOne {
	builder := c.Delete().Where(workflows.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WorkflowsDeleteOne{builder}
}

// Query returns a query builder for Workflows.
func (c *WorkflowsClient) Query() *WorkflowsQuery {
	return &WorkflowsQuery{
		config: c.config,
	}
}

// Get returns a Workflows entity by its id.
func (c *WorkflowsClient) Get(ctx context.Context, id int) (*Workflows, error) {
	return c.Query().Where(workflows.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WorkflowsClient) GetX(ctx context.Context, id int) *Workflows {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryWorkflows queries the workflows edge of a Workflows.
func (c *WorkflowsClient) QueryWorkflows(w *Workflows) *RepositoryQuery {
	query := &RepositoryQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := w.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(workflows.Table, workflows.FieldID, id),
			sqlgraph.To(repository.Table, repository.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, workflows.WorkflowsTable, workflows.WorkflowsColumn),
		)
		fromV = sqlgraph.Neighbors(w.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *WorkflowsClient) Hooks() []Hook {
	return c.hooks.Workflows
}
