// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/redhat-appstudio/quality-studio/pkg/storage/ent/db/codecov"
	"github.com/redhat-appstudio/quality-studio/pkg/storage/ent/db/predicate"
	"github.com/redhat-appstudio/quality-studio/pkg/storage/ent/db/repository"
)

// CodeCovQuery is the builder for querying CodeCov entities.
type CodeCovQuery struct {
	config
	limit       *int
	offset      *int
	unique      *bool
	order       []OrderFunc
	fields      []string
	predicates  []predicate.CodeCov
	withCodecov *RepositoryQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CodeCovQuery builder.
func (ccq *CodeCovQuery) Where(ps ...predicate.CodeCov) *CodeCovQuery {
	ccq.predicates = append(ccq.predicates, ps...)
	return ccq
}

// Limit adds a limit step to the query.
func (ccq *CodeCovQuery) Limit(limit int) *CodeCovQuery {
	ccq.limit = &limit
	return ccq
}

// Offset adds an offset step to the query.
func (ccq *CodeCovQuery) Offset(offset int) *CodeCovQuery {
	ccq.offset = &offset
	return ccq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ccq *CodeCovQuery) Unique(unique bool) *CodeCovQuery {
	ccq.unique = &unique
	return ccq
}

// Order adds an order step to the query.
func (ccq *CodeCovQuery) Order(o ...OrderFunc) *CodeCovQuery {
	ccq.order = append(ccq.order, o...)
	return ccq
}

// QueryCodecov chains the current query on the "codecov" edge.
func (ccq *CodeCovQuery) QueryCodecov() *RepositoryQuery {
	query := &RepositoryQuery{config: ccq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ccq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ccq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(codecov.Table, codecov.FieldID, selector),
			sqlgraph.To(repository.Table, repository.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, codecov.CodecovTable, codecov.CodecovColumn),
		)
		fromU = sqlgraph.SetNeighbors(ccq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CodeCov entity from the query.
// Returns a *NotFoundError when no CodeCov was found.
func (ccq *CodeCovQuery) First(ctx context.Context) (*CodeCov, error) {
	nodes, err := ccq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{codecov.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ccq *CodeCovQuery) FirstX(ctx context.Context) *CodeCov {
	node, err := ccq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CodeCov ID from the query.
// Returns a *NotFoundError when no CodeCov ID was found.
func (ccq *CodeCovQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ccq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{codecov.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ccq *CodeCovQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := ccq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CodeCov entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CodeCov entity is found.
// Returns a *NotFoundError when no CodeCov entities are found.
func (ccq *CodeCovQuery) Only(ctx context.Context) (*CodeCov, error) {
	nodes, err := ccq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{codecov.Label}
	default:
		return nil, &NotSingularError{codecov.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ccq *CodeCovQuery) OnlyX(ctx context.Context) *CodeCov {
	node, err := ccq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CodeCov ID in the query.
// Returns a *NotSingularError when more than one CodeCov ID is found.
// Returns a *NotFoundError when no entities are found.
func (ccq *CodeCovQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ccq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{codecov.Label}
	default:
		err = &NotSingularError{codecov.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ccq *CodeCovQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := ccq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CodeCovs.
func (ccq *CodeCovQuery) All(ctx context.Context) ([]*CodeCov, error) {
	if err := ccq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ccq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ccq *CodeCovQuery) AllX(ctx context.Context) []*CodeCov {
	nodes, err := ccq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CodeCov IDs.
func (ccq *CodeCovQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := ccq.Select(codecov.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ccq *CodeCovQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := ccq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ccq *CodeCovQuery) Count(ctx context.Context) (int, error) {
	if err := ccq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ccq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ccq *CodeCovQuery) CountX(ctx context.Context) int {
	count, err := ccq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ccq *CodeCovQuery) Exist(ctx context.Context) (bool, error) {
	if err := ccq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ccq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ccq *CodeCovQuery) ExistX(ctx context.Context) bool {
	exist, err := ccq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CodeCovQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ccq *CodeCovQuery) Clone() *CodeCovQuery {
	if ccq == nil {
		return nil
	}
	return &CodeCovQuery{
		config:      ccq.config,
		limit:       ccq.limit,
		offset:      ccq.offset,
		order:       append([]OrderFunc{}, ccq.order...),
		predicates:  append([]predicate.CodeCov{}, ccq.predicates...),
		withCodecov: ccq.withCodecov.Clone(),
		// clone intermediate query.
		sql:    ccq.sql.Clone(),
		path:   ccq.path,
		unique: ccq.unique,
	}
}

// WithCodecov tells the query-builder to eager-load the nodes that are connected to
// the "codecov" edge. The optional arguments are used to configure the query builder of the edge.
func (ccq *CodeCovQuery) WithCodecov(opts ...func(*RepositoryQuery)) *CodeCovQuery {
	query := &RepositoryQuery{config: ccq.config}
	for _, opt := range opts {
		opt(query)
	}
	ccq.withCodecov = query
	return ccq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RepositoryName string `json:"repository_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CodeCov.Query().
//		GroupBy(codecov.FieldRepositoryName).
//		Aggregate(db.Count()).
//		Scan(ctx, &v)
func (ccq *CodeCovQuery) GroupBy(field string, fields ...string) *CodeCovGroupBy {
	grbuild := &CodeCovGroupBy{config: ccq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ccq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ccq.sqlQuery(ctx), nil
	}
	grbuild.label = codecov.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RepositoryName string `json:"repository_name,omitempty"`
//	}
//
//	client.CodeCov.Query().
//		Select(codecov.FieldRepositoryName).
//		Scan(ctx, &v)
func (ccq *CodeCovQuery) Select(fields ...string) *CodeCovSelect {
	ccq.fields = append(ccq.fields, fields...)
	selbuild := &CodeCovSelect{CodeCovQuery: ccq}
	selbuild.label = codecov.Label
	selbuild.flds, selbuild.scan = &ccq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a CodeCovSelect configured with the given aggregations.
func (ccq *CodeCovQuery) Aggregate(fns ...AggregateFunc) *CodeCovSelect {
	return ccq.Select().Aggregate(fns...)
}

func (ccq *CodeCovQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ccq.fields {
		if !codecov.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if ccq.path != nil {
		prev, err := ccq.path(ctx)
		if err != nil {
			return err
		}
		ccq.sql = prev
	}
	return nil
}

func (ccq *CodeCovQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CodeCov, error) {
	var (
		nodes       = []*CodeCov{}
		withFKs     = ccq.withFKs
		_spec       = ccq.querySpec()
		loadedTypes = [1]bool{
			ccq.withCodecov != nil,
		}
	)
	if ccq.withCodecov != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, codecov.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CodeCov).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CodeCov{config: ccq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ccq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ccq.withCodecov; query != nil {
		if err := ccq.loadCodecov(ctx, query, nodes, nil,
			func(n *CodeCov, e *Repository) { n.Edges.Codecov = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ccq *CodeCovQuery) loadCodecov(ctx context.Context, query *RepositoryQuery, nodes []*CodeCov, init func(*CodeCov), assign func(*CodeCov, *Repository)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CodeCov)
	for i := range nodes {
		if nodes[i].repository_codecov == nil {
			continue
		}
		fk := *nodes[i].repository_codecov
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(repository.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "repository_codecov" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ccq *CodeCovQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ccq.querySpec()
	_spec.Node.Columns = ccq.fields
	if len(ccq.fields) > 0 {
		_spec.Unique = ccq.unique != nil && *ccq.unique
	}
	return sqlgraph.CountNodes(ctx, ccq.driver, _spec)
}

func (ccq *CodeCovQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := ccq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

func (ccq *CodeCovQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   codecov.Table,
			Columns: codecov.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: codecov.FieldID,
			},
		},
		From:   ccq.sql,
		Unique: true,
	}
	if unique := ccq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ccq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codecov.FieldID)
		for i := range fields {
			if fields[i] != codecov.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ccq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ccq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ccq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ccq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ccq *CodeCovQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ccq.driver.Dialect())
	t1 := builder.Table(codecov.Table)
	columns := ccq.fields
	if len(columns) == 0 {
		columns = codecov.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ccq.sql != nil {
		selector = ccq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ccq.unique != nil && *ccq.unique {
		selector.Distinct()
	}
	for _, p := range ccq.predicates {
		p(selector)
	}
	for _, p := range ccq.order {
		p(selector)
	}
	if offset := ccq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ccq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CodeCovGroupBy is the group-by builder for CodeCov entities.
type CodeCovGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ccgb *CodeCovGroupBy) Aggregate(fns ...AggregateFunc) *CodeCovGroupBy {
	ccgb.fns = append(ccgb.fns, fns...)
	return ccgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ccgb *CodeCovGroupBy) Scan(ctx context.Context, v any) error {
	query, err := ccgb.path(ctx)
	if err != nil {
		return err
	}
	ccgb.sql = query
	return ccgb.sqlScan(ctx, v)
}

func (ccgb *CodeCovGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range ccgb.fields {
		if !codecov.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ccgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ccgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ccgb *CodeCovGroupBy) sqlQuery() *sql.Selector {
	selector := ccgb.sql.Select()
	aggregation := make([]string, 0, len(ccgb.fns))
	for _, fn := range ccgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ccgb.fields)+len(ccgb.fns))
		for _, f := range ccgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ccgb.fields...)...)
}

// CodeCovSelect is the builder for selecting fields of CodeCov entities.
type CodeCovSelect struct {
	*CodeCovQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ccs *CodeCovSelect) Aggregate(fns ...AggregateFunc) *CodeCovSelect {
	ccs.fns = append(ccs.fns, fns...)
	return ccs
}

// Scan applies the selector query and scans the result into the given value.
func (ccs *CodeCovSelect) Scan(ctx context.Context, v any) error {
	if err := ccs.prepareQuery(ctx); err != nil {
		return err
	}
	ccs.sql = ccs.CodeCovQuery.sqlQuery(ctx)
	return ccs.sqlScan(ctx, v)
}

func (ccs *CodeCovSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(ccs.fns))
	for _, fn := range ccs.fns {
		aggregation = append(aggregation, fn(ccs.sql))
	}
	switch n := len(*ccs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		ccs.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		ccs.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := ccs.sql.Query()
	if err := ccs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
