// Code generated by ent, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/redhat-appstudio/quality-studio/pkg/storage/ent/db/prowsuites"
	"github.com/redhat-appstudio/quality-studio/pkg/storage/ent/db/repository"
)

// ProwSuites is the model entity for the ProwSuites schema.
type ProwSuites struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// JobID holds the value of the "job_id" field.
	JobID string `json:"job_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Time holds the value of the "time" field.
	Time float64 `json:"time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProwSuitesQuery when eager-loading is set.
	Edges                  ProwSuitesEdges `json:"edges"`
	repository_prow_suites *uuid.UUID
}

// ProwSuitesEdges holds the relations/edges for other nodes in the graph.
type ProwSuitesEdges struct {
	// ProwSuites holds the value of the prow_suites edge.
	ProwSuites *Repository `json:"prow_suites,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProwSuitesOrErr returns the ProwSuites value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProwSuitesEdges) ProwSuitesOrErr() (*Repository, error) {
	if e.loadedTypes[0] {
		if e.ProwSuites == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: repository.Label}
		}
		return e.ProwSuites, nil
	}
	return nil, &NotLoadedError{edge: "prow_suites"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProwSuites) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case prowsuites.FieldTime:
			values[i] = new(sql.NullFloat64)
		case prowsuites.FieldID:
			values[i] = new(sql.NullInt64)
		case prowsuites.FieldJobID, prowsuites.FieldName, prowsuites.FieldStatus:
			values[i] = new(sql.NullString)
		case prowsuites.ForeignKeys[0]: // repository_prow_suites
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			return nil, fmt.Errorf("unexpected column %q for type ProwSuites", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProwSuites fields.
func (ps *ProwSuites) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case prowsuites.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ps.ID = int(value.Int64)
		case prowsuites.FieldJobID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field job_id", values[i])
			} else if value.Valid {
				ps.JobID = value.String
			}
		case prowsuites.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ps.Name = value.String
			}
		case prowsuites.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ps.Status = value.String
			}
		case prowsuites.FieldTime:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field time", values[i])
			} else if value.Valid {
				ps.Time = value.Float64
			}
		case prowsuites.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field repository_prow_suites", values[i])
			} else if value.Valid {
				ps.repository_prow_suites = new(uuid.UUID)
				*ps.repository_prow_suites = *value.S.(*uuid.UUID)
			}
		}
	}
	return nil
}

// QueryProwSuites queries the "prow_suites" edge of the ProwSuites entity.
func (ps *ProwSuites) QueryProwSuites() *RepositoryQuery {
	return (&ProwSuitesClient{config: ps.config}).QueryProwSuites(ps)
}

// Update returns a builder for updating this ProwSuites.
// Note that you need to call ProwSuites.Unwrap() before calling this method if this ProwSuites
// was returned from a transaction, and the transaction was committed or rolled back.
func (ps *ProwSuites) Update() *ProwSuitesUpdateOne {
	return (&ProwSuitesClient{config: ps.config}).UpdateOne(ps)
}

// Unwrap unwraps the ProwSuites entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ps *ProwSuites) Unwrap() *ProwSuites {
	_tx, ok := ps.config.driver.(*txDriver)
	if !ok {
		panic("db: ProwSuites is not a transactional entity")
	}
	ps.config.driver = _tx.drv
	return ps
}

// String implements the fmt.Stringer.
func (ps *ProwSuites) String() string {
	var builder strings.Builder
	builder.WriteString("ProwSuites(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ps.ID))
	builder.WriteString("job_id=")
	builder.WriteString(ps.JobID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(ps.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(ps.Status)
	builder.WriteString(", ")
	builder.WriteString("time=")
	builder.WriteString(fmt.Sprintf("%v", ps.Time))
	builder.WriteByte(')')
	return builder.String()
}

// ProwSuitesSlice is a parsable slice of ProwSuites.
type ProwSuitesSlice []*ProwSuites

func (ps ProwSuitesSlice) config(cfg config) {
	for _i := range ps {
		ps[_i].config = cfg
	}
}
