// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/konflux-ci/quality-dashboard/pkg/storage/ent/db/codecov"
	"github.com/konflux-ci/quality-dashboard/pkg/storage/ent/db/oci"
	"github.com/konflux-ci/quality-dashboard/pkg/storage/ent/db/predicate"
	"github.com/konflux-ci/quality-dashboard/pkg/storage/ent/db/prowjobs"
	"github.com/konflux-ci/quality-dashboard/pkg/storage/ent/db/prowsuites"
	"github.com/konflux-ci/quality-dashboard/pkg/storage/ent/db/pullrequests"
	"github.com/konflux-ci/quality-dashboard/pkg/storage/ent/db/repository"
	"github.com/konflux-ci/quality-dashboard/pkg/storage/ent/db/teams"
	"github.com/konflux-ci/quality-dashboard/pkg/storage/ent/db/workflows"
)

// RepositoryUpdate is the builder for updating Repository entities.
type RepositoryUpdate struct {
	config
	hooks    []Hook
	mutation *RepositoryMutation
}

// Where appends a list predicates to the RepositoryUpdate builder.
func (ru *RepositoryUpdate) Where(ps ...predicate.Repository) *RepositoryUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetRepositoryName sets the "repository_name" field.
func (ru *RepositoryUpdate) SetRepositoryName(s string) *RepositoryUpdate {
	ru.mutation.SetRepositoryName(s)
	return ru
}

// SetNillableRepositoryName sets the "repository_name" field if the given value is not nil.
func (ru *RepositoryUpdate) SetNillableRepositoryName(s *string) *RepositoryUpdate {
	if s != nil {
		ru.SetRepositoryName(*s)
	}
	return ru
}

// SetGitOrganization sets the "git_organization" field.
func (ru *RepositoryUpdate) SetGitOrganization(s string) *RepositoryUpdate {
	ru.mutation.SetGitOrganization(s)
	return ru
}

// SetNillableGitOrganization sets the "git_organization" field if the given value is not nil.
func (ru *RepositoryUpdate) SetNillableGitOrganization(s *string) *RepositoryUpdate {
	if s != nil {
		ru.SetGitOrganization(*s)
	}
	return ru
}

// SetDescription sets the "description" field.
func (ru *RepositoryUpdate) SetDescription(s string) *RepositoryUpdate {
	ru.mutation.SetDescription(s)
	return ru
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ru *RepositoryUpdate) SetNillableDescription(s *string) *RepositoryUpdate {
	if s != nil {
		ru.SetDescription(*s)
	}
	return ru
}

// SetGitURL sets the "git_url" field.
func (ru *RepositoryUpdate) SetGitURL(s string) *RepositoryUpdate {
	ru.mutation.SetGitURL(s)
	return ru
}

// SetNillableGitURL sets the "git_url" field if the given value is not nil.
func (ru *RepositoryUpdate) SetNillableGitURL(s *string) *RepositoryUpdate {
	if s != nil {
		ru.SetGitURL(*s)
	}
	return ru
}

// SetRepositoriesID sets the "repositories" edge to the Teams entity by ID.
func (ru *RepositoryUpdate) SetRepositoriesID(id uuid.UUID) *RepositoryUpdate {
	ru.mutation.SetRepositoriesID(id)
	return ru
}

// SetNillableRepositoriesID sets the "repositories" edge to the Teams entity by ID if the given value is not nil.
func (ru *RepositoryUpdate) SetNillableRepositoriesID(id *uuid.UUID) *RepositoryUpdate {
	if id != nil {
		ru = ru.SetRepositoriesID(*id)
	}
	return ru
}

// SetRepositories sets the "repositories" edge to the Teams entity.
func (ru *RepositoryUpdate) SetRepositories(t *Teams) *RepositoryUpdate {
	return ru.SetRepositoriesID(t.ID)
}

// AddWorkflowIDs adds the "workflows" edge to the Workflows entity by IDs.
func (ru *RepositoryUpdate) AddWorkflowIDs(ids ...int) *RepositoryUpdate {
	ru.mutation.AddWorkflowIDs(ids...)
	return ru
}

// AddWorkflows adds the "workflows" edges to the Workflows entity.
func (ru *RepositoryUpdate) AddWorkflows(w ...*Workflows) *RepositoryUpdate {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return ru.AddWorkflowIDs(ids...)
}

// AddCodecovIDs adds the "codecov" edge to the CodeCov entity by IDs.
func (ru *RepositoryUpdate) AddCodecovIDs(ids ...uuid.UUID) *RepositoryUpdate {
	ru.mutation.AddCodecovIDs(ids...)
	return ru
}

// AddCodecov adds the "codecov" edges to the CodeCov entity.
func (ru *RepositoryUpdate) AddCodecov(c ...*CodeCov) *RepositoryUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ru.AddCodecovIDs(ids...)
}

// AddOciIDs adds the "oci" edge to the OCI entity by IDs.
func (ru *RepositoryUpdate) AddOciIDs(ids ...uuid.UUID) *RepositoryUpdate {
	ru.mutation.AddOciIDs(ids...)
	return ru
}

// AddOci adds the "oci" edges to the OCI entity.
func (ru *RepositoryUpdate) AddOci(o ...*OCI) *RepositoryUpdate {
	ids := make([]uuid.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ru.AddOciIDs(ids...)
}

// AddProwSuiteIDs adds the "prow_suites" edge to the ProwSuites entity by IDs.
func (ru *RepositoryUpdate) AddProwSuiteIDs(ids ...int) *RepositoryUpdate {
	ru.mutation.AddProwSuiteIDs(ids...)
	return ru
}

// AddProwSuites adds the "prow_suites" edges to the ProwSuites entity.
func (ru *RepositoryUpdate) AddProwSuites(p ...*ProwSuites) *RepositoryUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ru.AddProwSuiteIDs(ids...)
}

// AddProwJobIDs adds the "prow_jobs" edge to the ProwJobs entity by IDs.
func (ru *RepositoryUpdate) AddProwJobIDs(ids ...int) *RepositoryUpdate {
	ru.mutation.AddProwJobIDs(ids...)
	return ru
}

// AddProwJobs adds the "prow_jobs" edges to the ProwJobs entity.
func (ru *RepositoryUpdate) AddProwJobs(p ...*ProwJobs) *RepositoryUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ru.AddProwJobIDs(ids...)
}

// AddPrIDs adds the "prs" edge to the PullRequests entity by IDs.
func (ru *RepositoryUpdate) AddPrIDs(ids ...int) *RepositoryUpdate {
	ru.mutation.AddPrIDs(ids...)
	return ru
}

// AddPrs adds the "prs" edges to the PullRequests entity.
func (ru *RepositoryUpdate) AddPrs(p ...*PullRequests) *RepositoryUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ru.AddPrIDs(ids...)
}

// Mutation returns the RepositoryMutation object of the builder.
func (ru *RepositoryUpdate) Mutation() *RepositoryMutation {
	return ru.mutation
}

// ClearRepositories clears the "repositories" edge to the Teams entity.
func (ru *RepositoryUpdate) ClearRepositories() *RepositoryUpdate {
	ru.mutation.ClearRepositories()
	return ru
}

// ClearWorkflows clears all "workflows" edges to the Workflows entity.
func (ru *RepositoryUpdate) ClearWorkflows() *RepositoryUpdate {
	ru.mutation.ClearWorkflows()
	return ru
}

// RemoveWorkflowIDs removes the "workflows" edge to Workflows entities by IDs.
func (ru *RepositoryUpdate) RemoveWorkflowIDs(ids ...int) *RepositoryUpdate {
	ru.mutation.RemoveWorkflowIDs(ids...)
	return ru
}

// RemoveWorkflows removes "workflows" edges to Workflows entities.
func (ru *RepositoryUpdate) RemoveWorkflows(w ...*Workflows) *RepositoryUpdate {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return ru.RemoveWorkflowIDs(ids...)
}

// ClearCodecov clears all "codecov" edges to the CodeCov entity.
func (ru *RepositoryUpdate) ClearCodecov() *RepositoryUpdate {
	ru.mutation.ClearCodecov()
	return ru
}

// RemoveCodecovIDs removes the "codecov" edge to CodeCov entities by IDs.
func (ru *RepositoryUpdate) RemoveCodecovIDs(ids ...uuid.UUID) *RepositoryUpdate {
	ru.mutation.RemoveCodecovIDs(ids...)
	return ru
}

// RemoveCodecov removes "codecov" edges to CodeCov entities.
func (ru *RepositoryUpdate) RemoveCodecov(c ...*CodeCov) *RepositoryUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ru.RemoveCodecovIDs(ids...)
}

// ClearOci clears all "oci" edges to the OCI entity.
func (ru *RepositoryUpdate) ClearOci() *RepositoryUpdate {
	ru.mutation.ClearOci()
	return ru
}

// RemoveOciIDs removes the "oci" edge to OCI entities by IDs.
func (ru *RepositoryUpdate) RemoveOciIDs(ids ...uuid.UUID) *RepositoryUpdate {
	ru.mutation.RemoveOciIDs(ids...)
	return ru
}

// RemoveOci removes "oci" edges to OCI entities.
func (ru *RepositoryUpdate) RemoveOci(o ...*OCI) *RepositoryUpdate {
	ids := make([]uuid.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ru.RemoveOciIDs(ids...)
}

// ClearProwSuites clears all "prow_suites" edges to the ProwSuites entity.
func (ru *RepositoryUpdate) ClearProwSuites() *RepositoryUpdate {
	ru.mutation.ClearProwSuites()
	return ru
}

// RemoveProwSuiteIDs removes the "prow_suites" edge to ProwSuites entities by IDs.
func (ru *RepositoryUpdate) RemoveProwSuiteIDs(ids ...int) *RepositoryUpdate {
	ru.mutation.RemoveProwSuiteIDs(ids...)
	return ru
}

// RemoveProwSuites removes "prow_suites" edges to ProwSuites entities.
func (ru *RepositoryUpdate) RemoveProwSuites(p ...*ProwSuites) *RepositoryUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ru.RemoveProwSuiteIDs(ids...)
}

// ClearProwJobs clears all "prow_jobs" edges to the ProwJobs entity.
func (ru *RepositoryUpdate) ClearProwJobs() *RepositoryUpdate {
	ru.mutation.ClearProwJobs()
	return ru
}

// RemoveProwJobIDs removes the "prow_jobs" edge to ProwJobs entities by IDs.
func (ru *RepositoryUpdate) RemoveProwJobIDs(ids ...int) *RepositoryUpdate {
	ru.mutation.RemoveProwJobIDs(ids...)
	return ru
}

// RemoveProwJobs removes "prow_jobs" edges to ProwJobs entities.
func (ru *RepositoryUpdate) RemoveProwJobs(p ...*ProwJobs) *RepositoryUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ru.RemoveProwJobIDs(ids...)
}

// ClearPrs clears all "prs" edges to the PullRequests entity.
func (ru *RepositoryUpdate) ClearPrs() *RepositoryUpdate {
	ru.mutation.ClearPrs()
	return ru
}

// RemovePrIDs removes the "prs" edge to PullRequests entities by IDs.
func (ru *RepositoryUpdate) RemovePrIDs(ids ...int) *RepositoryUpdate {
	ru.mutation.RemovePrIDs(ids...)
	return ru
}

// RemovePrs removes "prs" edges to PullRequests entities.
func (ru *RepositoryUpdate) RemovePrs(p ...*PullRequests) *RepositoryUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ru.RemovePrIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RepositoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RepositoryUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RepositoryUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RepositoryUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *RepositoryUpdate) check() error {
	if v, ok := ru.mutation.RepositoryName(); ok {
		if err := repository.RepositoryNameValidator(v); err != nil {
			return &ValidationError{Name: "repository_name", err: fmt.Errorf(`db: validator failed for field "Repository.repository_name": %w`, err)}
		}
	}
	if v, ok := ru.mutation.GitOrganization(); ok {
		if err := repository.GitOrganizationValidator(v); err != nil {
			return &ValidationError{Name: "git_organization", err: fmt.Errorf(`db: validator failed for field "Repository.git_organization": %w`, err)}
		}
	}
	if v, ok := ru.mutation.Description(); ok {
		if err := repository.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`db: validator failed for field "Repository.description": %w`, err)}
		}
	}
	if v, ok := ru.mutation.GitURL(); ok {
		if err := repository.GitURLValidator(v); err != nil {
			return &ValidationError{Name: "git_url", err: fmt.Errorf(`db: validator failed for field "Repository.git_url": %w`, err)}
		}
	}
	return nil
}

func (ru *RepositoryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(repository.Table, repository.Columns, sqlgraph.NewFieldSpec(repository.FieldID, field.TypeString))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.RepositoryName(); ok {
		_spec.SetField(repository.FieldRepositoryName, field.TypeString, value)
	}
	if value, ok := ru.mutation.GitOrganization(); ok {
		_spec.SetField(repository.FieldGitOrganization, field.TypeString, value)
	}
	if value, ok := ru.mutation.Description(); ok {
		_spec.SetField(repository.FieldDescription, field.TypeString, value)
	}
	if value, ok := ru.mutation.GitURL(); ok {
		_spec.SetField(repository.FieldGitURL, field.TypeString, value)
	}
	if ru.mutation.RepositoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repository.RepositoriesTable,
			Columns: []string{repository.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teams.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RepositoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repository.RepositoriesTable,
			Columns: []string{repository.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teams.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.WorkflowsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.WorkflowsTable,
			Columns: []string{repository.WorkflowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflows.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RemovedWorkflowsIDs(); len(nodes) > 0 && !ru.mutation.WorkflowsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.WorkflowsTable,
			Columns: []string{repository.WorkflowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflows.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.WorkflowsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.WorkflowsTable,
			Columns: []string{repository.WorkflowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflows.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.CodecovCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.CodecovTable,
			Columns: []string{repository.CodecovColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codecov.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RemovedCodecovIDs(); len(nodes) > 0 && !ru.mutation.CodecovCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.CodecovTable,
			Columns: []string{repository.CodecovColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codecov.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.CodecovIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.CodecovTable,
			Columns: []string{repository.CodecovColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codecov.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.OciCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.OciTable,
			Columns: []string{repository.OciColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oci.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RemovedOciIDs(); len(nodes) > 0 && !ru.mutation.OciCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.OciTable,
			Columns: []string{repository.OciColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oci.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.OciIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.OciTable,
			Columns: []string{repository.OciColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oci.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.ProwSuitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ProwSuitesTable,
			Columns: []string{repository.ProwSuitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prowsuites.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RemovedProwSuitesIDs(); len(nodes) > 0 && !ru.mutation.ProwSuitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ProwSuitesTable,
			Columns: []string{repository.ProwSuitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prowsuites.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.ProwSuitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ProwSuitesTable,
			Columns: []string{repository.ProwSuitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prowsuites.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.ProwJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ProwJobsTable,
			Columns: []string{repository.ProwJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prowjobs.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RemovedProwJobsIDs(); len(nodes) > 0 && !ru.mutation.ProwJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ProwJobsTable,
			Columns: []string{repository.ProwJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prowjobs.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.ProwJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ProwJobsTable,
			Columns: []string{repository.ProwJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prowjobs.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.PrsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.PrsTable,
			Columns: []string{repository.PrsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pullrequests.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RemovedPrsIDs(); len(nodes) > 0 && !ru.mutation.PrsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.PrsTable,
			Columns: []string{repository.PrsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pullrequests.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.PrsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.PrsTable,
			Columns: []string{repository.PrsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pullrequests.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repository.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RepositoryUpdateOne is the builder for updating a single Repository entity.
type RepositoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RepositoryMutation
}

// SetRepositoryName sets the "repository_name" field.
func (ruo *RepositoryUpdateOne) SetRepositoryName(s string) *RepositoryUpdateOne {
	ruo.mutation.SetRepositoryName(s)
	return ruo
}

// SetNillableRepositoryName sets the "repository_name" field if the given value is not nil.
func (ruo *RepositoryUpdateOne) SetNillableRepositoryName(s *string) *RepositoryUpdateOne {
	if s != nil {
		ruo.SetRepositoryName(*s)
	}
	return ruo
}

// SetGitOrganization sets the "git_organization" field.
func (ruo *RepositoryUpdateOne) SetGitOrganization(s string) *RepositoryUpdateOne {
	ruo.mutation.SetGitOrganization(s)
	return ruo
}

// SetNillableGitOrganization sets the "git_organization" field if the given value is not nil.
func (ruo *RepositoryUpdateOne) SetNillableGitOrganization(s *string) *RepositoryUpdateOne {
	if s != nil {
		ruo.SetGitOrganization(*s)
	}
	return ruo
}

// SetDescription sets the "description" field.
func (ruo *RepositoryUpdateOne) SetDescription(s string) *RepositoryUpdateOne {
	ruo.mutation.SetDescription(s)
	return ruo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ruo *RepositoryUpdateOne) SetNillableDescription(s *string) *RepositoryUpdateOne {
	if s != nil {
		ruo.SetDescription(*s)
	}
	return ruo
}

// SetGitURL sets the "git_url" field.
func (ruo *RepositoryUpdateOne) SetGitURL(s string) *RepositoryUpdateOne {
	ruo.mutation.SetGitURL(s)
	return ruo
}

// SetNillableGitURL sets the "git_url" field if the given value is not nil.
func (ruo *RepositoryUpdateOne) SetNillableGitURL(s *string) *RepositoryUpdateOne {
	if s != nil {
		ruo.SetGitURL(*s)
	}
	return ruo
}

// SetRepositoriesID sets the "repositories" edge to the Teams entity by ID.
func (ruo *RepositoryUpdateOne) SetRepositoriesID(id uuid.UUID) *RepositoryUpdateOne {
	ruo.mutation.SetRepositoriesID(id)
	return ruo
}

// SetNillableRepositoriesID sets the "repositories" edge to the Teams entity by ID if the given value is not nil.
func (ruo *RepositoryUpdateOne) SetNillableRepositoriesID(id *uuid.UUID) *RepositoryUpdateOne {
	if id != nil {
		ruo = ruo.SetRepositoriesID(*id)
	}
	return ruo
}

// SetRepositories sets the "repositories" edge to the Teams entity.
func (ruo *RepositoryUpdateOne) SetRepositories(t *Teams) *RepositoryUpdateOne {
	return ruo.SetRepositoriesID(t.ID)
}

// AddWorkflowIDs adds the "workflows" edge to the Workflows entity by IDs.
func (ruo *RepositoryUpdateOne) AddWorkflowIDs(ids ...int) *RepositoryUpdateOne {
	ruo.mutation.AddWorkflowIDs(ids...)
	return ruo
}

// AddWorkflows adds the "workflows" edges to the Workflows entity.
func (ruo *RepositoryUpdateOne) AddWorkflows(w ...*Workflows) *RepositoryUpdateOne {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return ruo.AddWorkflowIDs(ids...)
}

// AddCodecovIDs adds the "codecov" edge to the CodeCov entity by IDs.
func (ruo *RepositoryUpdateOne) AddCodecovIDs(ids ...uuid.UUID) *RepositoryUpdateOne {
	ruo.mutation.AddCodecovIDs(ids...)
	return ruo
}

// AddCodecov adds the "codecov" edges to the CodeCov entity.
func (ruo *RepositoryUpdateOne) AddCodecov(c ...*CodeCov) *RepositoryUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ruo.AddCodecovIDs(ids...)
}

// AddOciIDs adds the "oci" edge to the OCI entity by IDs.
func (ruo *RepositoryUpdateOne) AddOciIDs(ids ...uuid.UUID) *RepositoryUpdateOne {
	ruo.mutation.AddOciIDs(ids...)
	return ruo
}

// AddOci adds the "oci" edges to the OCI entity.
func (ruo *RepositoryUpdateOne) AddOci(o ...*OCI) *RepositoryUpdateOne {
	ids := make([]uuid.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ruo.AddOciIDs(ids...)
}

// AddProwSuiteIDs adds the "prow_suites" edge to the ProwSuites entity by IDs.
func (ruo *RepositoryUpdateOne) AddProwSuiteIDs(ids ...int) *RepositoryUpdateOne {
	ruo.mutation.AddProwSuiteIDs(ids...)
	return ruo
}

// AddProwSuites adds the "prow_suites" edges to the ProwSuites entity.
func (ruo *RepositoryUpdateOne) AddProwSuites(p ...*ProwSuites) *RepositoryUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ruo.AddProwSuiteIDs(ids...)
}

// AddProwJobIDs adds the "prow_jobs" edge to the ProwJobs entity by IDs.
func (ruo *RepositoryUpdateOne) AddProwJobIDs(ids ...int) *RepositoryUpdateOne {
	ruo.mutation.AddProwJobIDs(ids...)
	return ruo
}

// AddProwJobs adds the "prow_jobs" edges to the ProwJobs entity.
func (ruo *RepositoryUpdateOne) AddProwJobs(p ...*ProwJobs) *RepositoryUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ruo.AddProwJobIDs(ids...)
}

// AddPrIDs adds the "prs" edge to the PullRequests entity by IDs.
func (ruo *RepositoryUpdateOne) AddPrIDs(ids ...int) *RepositoryUpdateOne {
	ruo.mutation.AddPrIDs(ids...)
	return ruo
}

// AddPrs adds the "prs" edges to the PullRequests entity.
func (ruo *RepositoryUpdateOne) AddPrs(p ...*PullRequests) *RepositoryUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ruo.AddPrIDs(ids...)
}

// Mutation returns the RepositoryMutation object of the builder.
func (ruo *RepositoryUpdateOne) Mutation() *RepositoryMutation {
	return ruo.mutation
}

// ClearRepositories clears the "repositories" edge to the Teams entity.
func (ruo *RepositoryUpdateOne) ClearRepositories() *RepositoryUpdateOne {
	ruo.mutation.ClearRepositories()
	return ruo
}

// ClearWorkflows clears all "workflows" edges to the Workflows entity.
func (ruo *RepositoryUpdateOne) ClearWorkflows() *RepositoryUpdateOne {
	ruo.mutation.ClearWorkflows()
	return ruo
}

// RemoveWorkflowIDs removes the "workflows" edge to Workflows entities by IDs.
func (ruo *RepositoryUpdateOne) RemoveWorkflowIDs(ids ...int) *RepositoryUpdateOne {
	ruo.mutation.RemoveWorkflowIDs(ids...)
	return ruo
}

// RemoveWorkflows removes "workflows" edges to Workflows entities.
func (ruo *RepositoryUpdateOne) RemoveWorkflows(w ...*Workflows) *RepositoryUpdateOne {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return ruo.RemoveWorkflowIDs(ids...)
}

// ClearCodecov clears all "codecov" edges to the CodeCov entity.
func (ruo *RepositoryUpdateOne) ClearCodecov() *RepositoryUpdateOne {
	ruo.mutation.ClearCodecov()
	return ruo
}

// RemoveCodecovIDs removes the "codecov" edge to CodeCov entities by IDs.
func (ruo *RepositoryUpdateOne) RemoveCodecovIDs(ids ...uuid.UUID) *RepositoryUpdateOne {
	ruo.mutation.RemoveCodecovIDs(ids...)
	return ruo
}

// RemoveCodecov removes "codecov" edges to CodeCov entities.
func (ruo *RepositoryUpdateOne) RemoveCodecov(c ...*CodeCov) *RepositoryUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ruo.RemoveCodecovIDs(ids...)
}

// ClearOci clears all "oci" edges to the OCI entity.
func (ruo *RepositoryUpdateOne) ClearOci() *RepositoryUpdateOne {
	ruo.mutation.ClearOci()
	return ruo
}

// RemoveOciIDs removes the "oci" edge to OCI entities by IDs.
func (ruo *RepositoryUpdateOne) RemoveOciIDs(ids ...uuid.UUID) *RepositoryUpdateOne {
	ruo.mutation.RemoveOciIDs(ids...)
	return ruo
}

// RemoveOci removes "oci" edges to OCI entities.
func (ruo *RepositoryUpdateOne) RemoveOci(o ...*OCI) *RepositoryUpdateOne {
	ids := make([]uuid.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ruo.RemoveOciIDs(ids...)
}

// ClearProwSuites clears all "prow_suites" edges to the ProwSuites entity.
func (ruo *RepositoryUpdateOne) ClearProwSuites() *RepositoryUpdateOne {
	ruo.mutation.ClearProwSuites()
	return ruo
}

// RemoveProwSuiteIDs removes the "prow_suites" edge to ProwSuites entities by IDs.
func (ruo *RepositoryUpdateOne) RemoveProwSuiteIDs(ids ...int) *RepositoryUpdateOne {
	ruo.mutation.RemoveProwSuiteIDs(ids...)
	return ruo
}

// RemoveProwSuites removes "prow_suites" edges to ProwSuites entities.
func (ruo *RepositoryUpdateOne) RemoveProwSuites(p ...*ProwSuites) *RepositoryUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ruo.RemoveProwSuiteIDs(ids...)
}

// ClearProwJobs clears all "prow_jobs" edges to the ProwJobs entity.
func (ruo *RepositoryUpdateOne) ClearProwJobs() *RepositoryUpdateOne {
	ruo.mutation.ClearProwJobs()
	return ruo
}

// RemoveProwJobIDs removes the "prow_jobs" edge to ProwJobs entities by IDs.
func (ruo *RepositoryUpdateOne) RemoveProwJobIDs(ids ...int) *RepositoryUpdateOne {
	ruo.mutation.RemoveProwJobIDs(ids...)
	return ruo
}

// RemoveProwJobs removes "prow_jobs" edges to ProwJobs entities.
func (ruo *RepositoryUpdateOne) RemoveProwJobs(p ...*ProwJobs) *RepositoryUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ruo.RemoveProwJobIDs(ids...)
}

// ClearPrs clears all "prs" edges to the PullRequests entity.
func (ruo *RepositoryUpdateOne) ClearPrs() *RepositoryUpdateOne {
	ruo.mutation.ClearPrs()
	return ruo
}

// RemovePrIDs removes the "prs" edge to PullRequests entities by IDs.
func (ruo *RepositoryUpdateOne) RemovePrIDs(ids ...int) *RepositoryUpdateOne {
	ruo.mutation.RemovePrIDs(ids...)
	return ruo
}

// RemovePrs removes "prs" edges to PullRequests entities.
func (ruo *RepositoryUpdateOne) RemovePrs(p ...*PullRequests) *RepositoryUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ruo.RemovePrIDs(ids...)
}

// Where appends a list predicates to the RepositoryUpdate builder.
func (ruo *RepositoryUpdateOne) Where(ps ...predicate.Repository) *RepositoryUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RepositoryUpdateOne) Select(field string, fields ...string) *RepositoryUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Repository entity.
func (ruo *RepositoryUpdateOne) Save(ctx context.Context) (*Repository, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RepositoryUpdateOne) SaveX(ctx context.Context) *Repository {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RepositoryUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RepositoryUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *RepositoryUpdateOne) check() error {
	if v, ok := ruo.mutation.RepositoryName(); ok {
		if err := repository.RepositoryNameValidator(v); err != nil {
			return &ValidationError{Name: "repository_name", err: fmt.Errorf(`db: validator failed for field "Repository.repository_name": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.GitOrganization(); ok {
		if err := repository.GitOrganizationValidator(v); err != nil {
			return &ValidationError{Name: "git_organization", err: fmt.Errorf(`db: validator failed for field "Repository.git_organization": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.Description(); ok {
		if err := repository.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`db: validator failed for field "Repository.description": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.GitURL(); ok {
		if err := repository.GitURLValidator(v); err != nil {
			return &ValidationError{Name: "git_url", err: fmt.Errorf(`db: validator failed for field "Repository.git_url": %w`, err)}
		}
	}
	return nil
}

func (ruo *RepositoryUpdateOne) sqlSave(ctx context.Context) (_node *Repository, err error) {
	if err := ruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repository.Table, repository.Columns, sqlgraph.NewFieldSpec(repository.FieldID, field.TypeString))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "Repository.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repository.FieldID)
		for _, f := range fields {
			if !repository.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != repository.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.RepositoryName(); ok {
		_spec.SetField(repository.FieldRepositoryName, field.TypeString, value)
	}
	if value, ok := ruo.mutation.GitOrganization(); ok {
		_spec.SetField(repository.FieldGitOrganization, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Description(); ok {
		_spec.SetField(repository.FieldDescription, field.TypeString, value)
	}
	if value, ok := ruo.mutation.GitURL(); ok {
		_spec.SetField(repository.FieldGitURL, field.TypeString, value)
	}
	if ruo.mutation.RepositoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repository.RepositoriesTable,
			Columns: []string{repository.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teams.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RepositoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repository.RepositoriesTable,
			Columns: []string{repository.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teams.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.WorkflowsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.WorkflowsTable,
			Columns: []string{repository.WorkflowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflows.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RemovedWorkflowsIDs(); len(nodes) > 0 && !ruo.mutation.WorkflowsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.WorkflowsTable,
			Columns: []string{repository.WorkflowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflows.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.WorkflowsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.WorkflowsTable,
			Columns: []string{repository.WorkflowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflows.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.CodecovCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.CodecovTable,
			Columns: []string{repository.CodecovColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codecov.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RemovedCodecovIDs(); len(nodes) > 0 && !ruo.mutation.CodecovCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.CodecovTable,
			Columns: []string{repository.CodecovColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codecov.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.CodecovIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.CodecovTable,
			Columns: []string{repository.CodecovColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codecov.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.OciCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.OciTable,
			Columns: []string{repository.OciColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oci.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RemovedOciIDs(); len(nodes) > 0 && !ruo.mutation.OciCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.OciTable,
			Columns: []string{repository.OciColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oci.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.OciIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.OciTable,
			Columns: []string{repository.OciColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oci.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.ProwSuitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ProwSuitesTable,
			Columns: []string{repository.ProwSuitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prowsuites.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RemovedProwSuitesIDs(); len(nodes) > 0 && !ruo.mutation.ProwSuitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ProwSuitesTable,
			Columns: []string{repository.ProwSuitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prowsuites.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.ProwSuitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ProwSuitesTable,
			Columns: []string{repository.ProwSuitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prowsuites.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.ProwJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ProwJobsTable,
			Columns: []string{repository.ProwJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prowjobs.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RemovedProwJobsIDs(); len(nodes) > 0 && !ruo.mutation.ProwJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ProwJobsTable,
			Columns: []string{repository.ProwJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prowjobs.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.ProwJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.ProwJobsTable,
			Columns: []string{repository.ProwJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prowjobs.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.PrsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.PrsTable,
			Columns: []string{repository.PrsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pullrequests.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RemovedPrsIDs(); len(nodes) > 0 && !ruo.mutation.PrsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.PrsTable,
			Columns: []string{repository.PrsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pullrequests.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.PrsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.PrsTable,
			Columns: []string{repository.PrsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pullrequests.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Repository{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repository.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
