// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/redhat-appstudio/quality-studio/pkg/storage/ent/db/codecov"
	"github.com/redhat-appstudio/quality-studio/pkg/storage/ent/db/predicate"
	"github.com/redhat-appstudio/quality-studio/pkg/storage/ent/db/prowjobs"
	"github.com/redhat-appstudio/quality-studio/pkg/storage/ent/db/prowsuites"
	"github.com/redhat-appstudio/quality-studio/pkg/storage/ent/db/repository"
	"github.com/redhat-appstudio/quality-studio/pkg/storage/ent/db/teams"
	"github.com/redhat-appstudio/quality-studio/pkg/storage/ent/db/workflows"
)

// RepositoryQuery is the builder for querying Repository entities.
type RepositoryQuery struct {
	config
	limit            *int
	offset           *int
	unique           *bool
	order            []OrderFunc
	fields           []string
	predicates       []predicate.Repository
	withRepositories *TeamsQuery
	withWorkflows    *WorkflowsQuery
	withCodecov      *CodeCovQuery
	withProwSuites   *ProwSuitesQuery
	withProwJobs     *ProwJobsQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RepositoryQuery builder.
func (rq *RepositoryQuery) Where(ps ...predicate.Repository) *RepositoryQuery {
	rq.predicates = append(rq.predicates, ps...)
	return rq
}

// Limit adds a limit step to the query.
func (rq *RepositoryQuery) Limit(limit int) *RepositoryQuery {
	rq.limit = &limit
	return rq
}

// Offset adds an offset step to the query.
func (rq *RepositoryQuery) Offset(offset int) *RepositoryQuery {
	rq.offset = &offset
	return rq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rq *RepositoryQuery) Unique(unique bool) *RepositoryQuery {
	rq.unique = &unique
	return rq
}

// Order adds an order step to the query.
func (rq *RepositoryQuery) Order(o ...OrderFunc) *RepositoryQuery {
	rq.order = append(rq.order, o...)
	return rq
}

// QueryRepositories chains the current query on the "repositories" edge.
func (rq *RepositoryQuery) QueryRepositories() *TeamsQuery {
	query := &TeamsQuery{config: rq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(repository.Table, repository.FieldID, selector),
			sqlgraph.To(teams.Table, teams.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, repository.RepositoriesTable, repository.RepositoriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorkflows chains the current query on the "workflows" edge.
func (rq *RepositoryQuery) QueryWorkflows() *WorkflowsQuery {
	query := &WorkflowsQuery{config: rq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(repository.Table, repository.FieldID, selector),
			sqlgraph.To(workflows.Table, workflows.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, repository.WorkflowsTable, repository.WorkflowsColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCodecov chains the current query on the "codecov" edge.
func (rq *RepositoryQuery) QueryCodecov() *CodeCovQuery {
	query := &CodeCovQuery{config: rq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(repository.Table, repository.FieldID, selector),
			sqlgraph.To(codecov.Table, codecov.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, repository.CodecovTable, repository.CodecovColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProwSuites chains the current query on the "prow_suites" edge.
func (rq *RepositoryQuery) QueryProwSuites() *ProwSuitesQuery {
	query := &ProwSuitesQuery{config: rq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(repository.Table, repository.FieldID, selector),
			sqlgraph.To(prowsuites.Table, prowsuites.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, repository.ProwSuitesTable, repository.ProwSuitesColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProwJobs chains the current query on the "prow_jobs" edge.
func (rq *RepositoryQuery) QueryProwJobs() *ProwJobsQuery {
	query := &ProwJobsQuery{config: rq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(repository.Table, repository.FieldID, selector),
			sqlgraph.To(prowjobs.Table, prowjobs.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, repository.ProwJobsTable, repository.ProwJobsColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Repository entity from the query.
// Returns a *NotFoundError when no Repository was found.
func (rq *RepositoryQuery) First(ctx context.Context) (*Repository, error) {
	nodes, err := rq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{repository.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rq *RepositoryQuery) FirstX(ctx context.Context) *Repository {
	node, err := rq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Repository ID from the query.
// Returns a *NotFoundError when no Repository ID was found.
func (rq *RepositoryQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{repository.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rq *RepositoryQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := rq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Repository entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Repository entity is found.
// Returns a *NotFoundError when no Repository entities are found.
func (rq *RepositoryQuery) Only(ctx context.Context) (*Repository, error) {
	nodes, err := rq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{repository.Label}
	default:
		return nil, &NotSingularError{repository.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rq *RepositoryQuery) OnlyX(ctx context.Context) *Repository {
	node, err := rq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Repository ID in the query.
// Returns a *NotSingularError when more than one Repository ID is found.
// Returns a *NotFoundError when no entities are found.
func (rq *RepositoryQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{repository.Label}
	default:
		err = &NotSingularError{repository.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rq *RepositoryQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := rq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Repositories.
func (rq *RepositoryQuery) All(ctx context.Context) ([]*Repository, error) {
	if err := rq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return rq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (rq *RepositoryQuery) AllX(ctx context.Context) []*Repository {
	nodes, err := rq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Repository IDs.
func (rq *RepositoryQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := rq.Select(repository.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rq *RepositoryQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := rq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rq *RepositoryQuery) Count(ctx context.Context) (int, error) {
	if err := rq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return rq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (rq *RepositoryQuery) CountX(ctx context.Context) int {
	count, err := rq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rq *RepositoryQuery) Exist(ctx context.Context) (bool, error) {
	if err := rq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return rq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (rq *RepositoryQuery) ExistX(ctx context.Context) bool {
	exist, err := rq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RepositoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rq *RepositoryQuery) Clone() *RepositoryQuery {
	if rq == nil {
		return nil
	}
	return &RepositoryQuery{
		config:           rq.config,
		limit:            rq.limit,
		offset:           rq.offset,
		order:            append([]OrderFunc{}, rq.order...),
		predicates:       append([]predicate.Repository{}, rq.predicates...),
		withRepositories: rq.withRepositories.Clone(),
		withWorkflows:    rq.withWorkflows.Clone(),
		withCodecov:      rq.withCodecov.Clone(),
		withProwSuites:   rq.withProwSuites.Clone(),
		withProwJobs:     rq.withProwJobs.Clone(),
		// clone intermediate query.
		sql:    rq.sql.Clone(),
		path:   rq.path,
		unique: rq.unique,
	}
}

// WithRepositories tells the query-builder to eager-load the nodes that are connected to
// the "repositories" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *RepositoryQuery) WithRepositories(opts ...func(*TeamsQuery)) *RepositoryQuery {
	query := &TeamsQuery{config: rq.config}
	for _, opt := range opts {
		opt(query)
	}
	rq.withRepositories = query
	return rq
}

// WithWorkflows tells the query-builder to eager-load the nodes that are connected to
// the "workflows" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *RepositoryQuery) WithWorkflows(opts ...func(*WorkflowsQuery)) *RepositoryQuery {
	query := &WorkflowsQuery{config: rq.config}
	for _, opt := range opts {
		opt(query)
	}
	rq.withWorkflows = query
	return rq
}

// WithCodecov tells the query-builder to eager-load the nodes that are connected to
// the "codecov" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *RepositoryQuery) WithCodecov(opts ...func(*CodeCovQuery)) *RepositoryQuery {
	query := &CodeCovQuery{config: rq.config}
	for _, opt := range opts {
		opt(query)
	}
	rq.withCodecov = query
	return rq
}

// WithProwSuites tells the query-builder to eager-load the nodes that are connected to
// the "prow_suites" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *RepositoryQuery) WithProwSuites(opts ...func(*ProwSuitesQuery)) *RepositoryQuery {
	query := &ProwSuitesQuery{config: rq.config}
	for _, opt := range opts {
		opt(query)
	}
	rq.withProwSuites = query
	return rq
}

// WithProwJobs tells the query-builder to eager-load the nodes that are connected to
// the "prow_jobs" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *RepositoryQuery) WithProwJobs(opts ...func(*ProwJobsQuery)) *RepositoryQuery {
	query := &ProwJobsQuery{config: rq.config}
	for _, opt := range opts {
		opt(query)
	}
	rq.withProwJobs = query
	return rq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RepositoryName string `json:"repository_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Repository.Query().
//		GroupBy(repository.FieldRepositoryName).
//		Aggregate(db.Count()).
//		Scan(ctx, &v)
func (rq *RepositoryQuery) GroupBy(field string, fields ...string) *RepositoryGroupBy {
	grbuild := &RepositoryGroupBy{config: rq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rq.sqlQuery(ctx), nil
	}
	grbuild.label = repository.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RepositoryName string `json:"repository_name,omitempty"`
//	}
//
//	client.Repository.Query().
//		Select(repository.FieldRepositoryName).
//		Scan(ctx, &v)
func (rq *RepositoryQuery) Select(fields ...string) *RepositorySelect {
	rq.fields = append(rq.fields, fields...)
	selbuild := &RepositorySelect{RepositoryQuery: rq}
	selbuild.label = repository.Label
	selbuild.flds, selbuild.scan = &rq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a RepositorySelect configured with the given aggregations.
func (rq *RepositoryQuery) Aggregate(fns ...AggregateFunc) *RepositorySelect {
	return rq.Select().Aggregate(fns...)
}

func (rq *RepositoryQuery) prepareQuery(ctx context.Context) error {
	for _, f := range rq.fields {
		if !repository.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if rq.path != nil {
		prev, err := rq.path(ctx)
		if err != nil {
			return err
		}
		rq.sql = prev
	}
	return nil
}

func (rq *RepositoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Repository, error) {
	var (
		nodes       = []*Repository{}
		withFKs     = rq.withFKs
		_spec       = rq.querySpec()
		loadedTypes = [5]bool{
			rq.withRepositories != nil,
			rq.withWorkflows != nil,
			rq.withCodecov != nil,
			rq.withProwSuites != nil,
			rq.withProwJobs != nil,
		}
	)
	if rq.withRepositories != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, repository.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Repository).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Repository{config: rq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rq.withRepositories; query != nil {
		if err := rq.loadRepositories(ctx, query, nodes, nil,
			func(n *Repository, e *Teams) { n.Edges.Repositories = e }); err != nil {
			return nil, err
		}
	}
	if query := rq.withWorkflows; query != nil {
		if err := rq.loadWorkflows(ctx, query, nodes,
			func(n *Repository) { n.Edges.Workflows = []*Workflows{} },
			func(n *Repository, e *Workflows) { n.Edges.Workflows = append(n.Edges.Workflows, e) }); err != nil {
			return nil, err
		}
	}
	if query := rq.withCodecov; query != nil {
		if err := rq.loadCodecov(ctx, query, nodes,
			func(n *Repository) { n.Edges.Codecov = []*CodeCov{} },
			func(n *Repository, e *CodeCov) { n.Edges.Codecov = append(n.Edges.Codecov, e) }); err != nil {
			return nil, err
		}
	}
	if query := rq.withProwSuites; query != nil {
		if err := rq.loadProwSuites(ctx, query, nodes,
			func(n *Repository) { n.Edges.ProwSuites = []*ProwSuites{} },
			func(n *Repository, e *ProwSuites) { n.Edges.ProwSuites = append(n.Edges.ProwSuites, e) }); err != nil {
			return nil, err
		}
	}
	if query := rq.withProwJobs; query != nil {
		if err := rq.loadProwJobs(ctx, query, nodes,
			func(n *Repository) { n.Edges.ProwJobs = []*ProwJobs{} },
			func(n *Repository, e *ProwJobs) { n.Edges.ProwJobs = append(n.Edges.ProwJobs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rq *RepositoryQuery) loadRepositories(ctx context.Context, query *TeamsQuery, nodes []*Repository, init func(*Repository), assign func(*Repository, *Teams)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Repository)
	for i := range nodes {
		if nodes[i].teams_repositories == nil {
			continue
		}
		fk := *nodes[i].teams_repositories
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(teams.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "teams_repositories" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (rq *RepositoryQuery) loadWorkflows(ctx context.Context, query *WorkflowsQuery, nodes []*Repository, init func(*Repository), assign func(*Repository, *Workflows)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Repository)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Workflows(func(s *sql.Selector) {
		s.Where(sql.InValues(repository.WorkflowsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.repository_workflows
		if fk == nil {
			return fmt.Errorf(`foreign-key "repository_workflows" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "repository_workflows" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (rq *RepositoryQuery) loadCodecov(ctx context.Context, query *CodeCovQuery, nodes []*Repository, init func(*Repository), assign func(*Repository, *CodeCov)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Repository)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.CodeCov(func(s *sql.Selector) {
		s.Where(sql.InValues(repository.CodecovColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.repository_codecov
		if fk == nil {
			return fmt.Errorf(`foreign-key "repository_codecov" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "repository_codecov" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (rq *RepositoryQuery) loadProwSuites(ctx context.Context, query *ProwSuitesQuery, nodes []*Repository, init func(*Repository), assign func(*Repository, *ProwSuites)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Repository)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ProwSuites(func(s *sql.Selector) {
		s.Where(sql.InValues(repository.ProwSuitesColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.repository_prow_suites
		if fk == nil {
			return fmt.Errorf(`foreign-key "repository_prow_suites" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "repository_prow_suites" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (rq *RepositoryQuery) loadProwJobs(ctx context.Context, query *ProwJobsQuery, nodes []*Repository, init func(*Repository), assign func(*Repository, *ProwJobs)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Repository)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ProwJobs(func(s *sql.Selector) {
		s.Where(sql.InValues(repository.ProwJobsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.repository_prow_jobs
		if fk == nil {
			return fmt.Errorf(`foreign-key "repository_prow_jobs" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "repository_prow_jobs" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (rq *RepositoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rq.querySpec()
	_spec.Node.Columns = rq.fields
	if len(rq.fields) > 0 {
		_spec.Unique = rq.unique != nil && *rq.unique
	}
	return sqlgraph.CountNodes(ctx, rq.driver, _spec)
}

func (rq *RepositoryQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := rq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

func (rq *RepositoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   repository.Table,
			Columns: repository.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: repository.FieldID,
			},
		},
		From:   rq.sql,
		Unique: true,
	}
	if unique := rq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repository.FieldID)
		for i := range fields {
			if fields[i] != repository.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rq *RepositoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rq.driver.Dialect())
	t1 := builder.Table(repository.Table)
	columns := rq.fields
	if len(columns) == 0 {
		columns = repository.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rq.sql != nil {
		selector = rq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rq.unique != nil && *rq.unique {
		selector.Distinct()
	}
	for _, p := range rq.predicates {
		p(selector)
	}
	for _, p := range rq.order {
		p(selector)
	}
	if offset := rq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RepositoryGroupBy is the group-by builder for Repository entities.
type RepositoryGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rgb *RepositoryGroupBy) Aggregate(fns ...AggregateFunc) *RepositoryGroupBy {
	rgb.fns = append(rgb.fns, fns...)
	return rgb
}

// Scan applies the group-by query and scans the result into the given value.
func (rgb *RepositoryGroupBy) Scan(ctx context.Context, v any) error {
	query, err := rgb.path(ctx)
	if err != nil {
		return err
	}
	rgb.sql = query
	return rgb.sqlScan(ctx, v)
}

func (rgb *RepositoryGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range rgb.fields {
		if !repository.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := rgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rgb *RepositoryGroupBy) sqlQuery() *sql.Selector {
	selector := rgb.sql.Select()
	aggregation := make([]string, 0, len(rgb.fns))
	for _, fn := range rgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(rgb.fields)+len(rgb.fns))
		for _, f := range rgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(rgb.fields...)...)
}

// RepositorySelect is the builder for selecting fields of Repository entities.
type RepositorySelect struct {
	*RepositoryQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rs *RepositorySelect) Aggregate(fns ...AggregateFunc) *RepositorySelect {
	rs.fns = append(rs.fns, fns...)
	return rs
}

// Scan applies the selector query and scans the result into the given value.
func (rs *RepositorySelect) Scan(ctx context.Context, v any) error {
	if err := rs.prepareQuery(ctx); err != nil {
		return err
	}
	rs.sql = rs.RepositoryQuery.sqlQuery(ctx)
	return rs.sqlScan(ctx, v)
}

func (rs *RepositorySelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(rs.fns))
	for _, fn := range rs.fns {
		aggregation = append(aggregation, fn(rs.sql))
	}
	switch n := len(*rs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		rs.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		rs.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := rs.sql.Query()
	if err := rs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
