kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: backend
spec:
  to:
    kind: Service
    name: backend
  port:
    targetPort: 8000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect