apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: dashboard-frontend-on-push
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" && target_branch == "main"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: "quay.io/konflux-ci/quality-dashboard-frontend:{{revision}}"
    - name: path-context
      value: "frontend"
    - name: infra-deployment-update-script
      value: |
        sed -i -E 's/[0-9a-f]{40}/{{ revision }}/g' components/quality-dashboard/base/backend/kustomization.yaml
        sed -i -E 's/[0-9a-f]{40}/{{ revision }}/g' components/quality-dashboard/base/dex/kustomization.yaml
        sed -i -E 's/[0-9a-f]{40}/{{ revision }}/g' components/quality-dashboard/base/frontend/kustomization.yaml
  pipelineRef:
    resolver: bundles
    params:
      - name: name
        value: docker-build
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/pipeline-core-services-docker-build:latest
      - name: kind
        value: Pipeline
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
