// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bugs is the predicate function for bugs builders.
type Bugs func(*sql.Selector)

// CodeCov is the predicate function for codecov builders.
type CodeCov func(*sql.Selector)

// Failure is the predicate function for failure builders.
type Failure func(*sql.Selector)

// Plugins is the predicate function for plugins builders.
type Plugins func(*sql.Selector)

// ProwJobs is the predicate function for prowjobs builders.
type ProwJobs func(*sql.Selector)

// ProwSuites is the predicate function for prowsuites builders.
type ProwSuites func(*sql.Selector)

// PullRequests is the predicate function for pullrequests builders.
type PullRequests func(*sql.Selector)

// Repository is the predicate function for repository builders.
type Repository func(*sql.Selector)

// Teams is the predicate function for teams builders.
type Teams func(*sql.Selector)

// Workflows is the predicate function for workflows builders.
type Workflows func(*sql.Selector)
